### ISSUE TITLE
Using Openldap and Istio Ingress

### ISSUE THREAD

**Issue by vbottu** [OpenUnison/openunison-k8s-login-activedirectory#70]
Hi,
I am trying to implement openunison for authn and authz of my on prem k8s cluster , One of the prerequisites is to have nginx ingress controller installed on the cluster, our cluster does not have it instead we are using istio as our service mesh. Would appreciate if you can help understand on how to use istio ingress gateway. I am not sure if I can use the IP of the kubernetes master to access the openunison app once deployed. 

Thanks.

**Comment by mlbiam** [comment]
You wouldn't use the IP.  The two hosts you define in values.yaml must point to your cluster's load balancer.  That said, Itsio ingress should be fine.  Once you run the orchestra helm chart, an `Ingress` object called `openunison` is created in the `openunison` namespace.  The metadata will look like:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/backend-protocol: https
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: openunison-orchestra
    nginx.org/ssl-services: openunison-orchestra
```
The first step would be to remove the nginx annotations and set the class to itsio:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
```
We don't need an istio sidecar so not sure how to exclude that.  Its already listening on port 8443 with a self signed certificate.

**Comment by vbottu** [comment]
we don’t have a load balancer attached to the cluster at the moment. All the services are exposed through istio’s virtualservices.

**Comment by vbottu** [comment]
Is there any other way of implementing this without having the domain names?

**Comment by mlbiam** [comment]
If you can expose one service via two virtualservices it should work.  Set your hosts to the IPs you configure in your virtualservice and it should work OK.  The operator doesn't create a virtual service so you'll need to create one on your own for the openunison-orchestra service.

**Comment by vbottu** [comment]
I tried deploying using the helm chart , but only crd and clusterrole and rolebinding were created and I see no pods in the namespace other than operator pod. I am confused about the network.openunison.host value. What should be given in the field . Is it the operator pod host?

**Comment by mlbiam** [comment]
> I tried deploying using the helm chart , but only crd and clusterrole and rolebinding were created and I see no pods in the namespace other than operator pod

The deployment is a 3 step process:

1. Deploy the operator helm chart (this will create the operator pod)
2. Create the secret
3. Deploy the openunison-orchestra helm chart which will deploy openunison as a deployment along with a service, ingress, secrets, etc.

> I am confused about the network.openunison.host value. What should be given in the field . Is it the operator pod host?

`network.openunison.host` will be the virtual ip assigned the the host of your istio virtualService.

**Comment by vbottu** [comment]
OK, here is what I have tried so far, 
deployed openldap and populated with sample users and groups
deployed openunison operator 
created secret as describe above
here are the hsot details from my values yaml
 ```
 openunison_host: "hostname:31076/openunison/"
  dashboard_host: "hostname:31076/dashboard/"
  api_server_host: "kubernetes master ip:6443"
  session_inactivity_timeout_seconds: 900
  k8s_url: https://kuberntesmaster-ip:6443 
```
I have deployed ngnix ingress controller and exposing dashboard using that
For some reason the ingress is not created for openunison ,i manually created the ingress in openunison namespace, you can see it below
```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openunison-ingress
  namespace: openunison
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/backend-protocol: https
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: openunison-orchestra
    nginx.org/ssl-services: openunison-orchestra
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: kubernetes-master-host-ip
      http:
        paths:
        - path: /openunison/
          backend:
            serviceName: openunison-orchestra
            servicePort: 443
```
the orchestra pod is running and when i try to hit `https://${ingress-host}:${ingress-port}` it giving me 404 
I am not sure if I am missing something here.
