### ISSUE TITLE
Show Icons to only who has access to cluster in multi cluster authentication

### ISSUE THREAD

**Issue by vbottu** [OpenUnison/openunison-k8s-login-activedirectory#79]
I've implemented multi cluster authentication portal leveraging login active directory as the management cluster and login-oidc as satellite clusters , I want to only show the icons for satellite cluster to a user if he has access to those clusters. Is there any way that i could acheive this.
I have this in the org and portalUrl
azRules:
  - constraint: o=Tremolo
    scope: dn

**Comment by mlbiam** [comment]
in either the `org` or the `portalUrl` you can specify a constraint by group in the same way you would specify it in the rbac rule.  So similar to the example in the README to limit access to the `CN=k8s_login_ckuster_admins,CN=Users,DC=ent2k12,DC=domain,DC=com` group, specify

```
  - constraint: CN=k8s_login_ckuster_admins,CN=Users,DC=ent2k12,DC=domain,DC=com
    scope: group
```

make sure you don't keep the original constraint in place otherwise everyone will see it.

**Comment by vbottu** [comment]
Thanks, how do I add multiple groups to that constraint, is it comma separated or a separate entry

**Comment by mlbiam** [comment]
You can list multiple `azRule`s:

```
apiVersion: openunison.tremolo.io/v1
kind: Org
metadata:
  name: cluster2
  namespace: openunison
spec:
  description: "My second cluster"
  uuid: 04901973-5f4c-46d9-9e22-55e88e168776
  parent: B158BD40-0C1B-11E3-8FFD-0800200C9A66
  showInPortal: true
  showInRequestAccess: false
  showInReports: false
  azRules:
  - scope: group
    constraint: CN=k8s_login_ckuster_admins,CN=Users,DC=ent2k12,DC=domain,DC=com
  - scope: group
    constraint: CN=k8s_login_cluster2_admins,CN=Users,DC=ent2k12,DC=domain,DC=com
```

When listing multiple groups, OpenUnison will allow access if **any** of the `azRule` definitions are satisfied

**Comment by vbottu** [comment]
I tried that ,the org is not displayed even though I the azRule is satisfied. Below is my org 
```
apiVersion: openunison.tremolo.io/v1
kind: Org
metadata:
  name: test-cluster
  namespace: openunison
spec:
  description: "TEST K8S CLUSTER"
  uuid: *************************************
  parent: ******************************
  showInPortal: true
  showInRequestAccess: false
  showInReports: false
  azRules:
  - scope: group
    constraint: CN=k8s-test-devs,OU=Groups,DC=example,DC=com
  - scope: group
    constraint: CN=k8s-test-admins,OU=Groups,DC=example,DC=com
```

**Comment by mlbiam** [comment]
try 

```
apiVersion: openunison.tremolo.io/v1
kind: Org
metadata:
  name: test-cluster
  namespace: openunison
spec:
  description: "TEST K8S CLUSTER"
  uuid: *************************************
  parent: ******************************
  showInPortal: true
  showInRequestAccess: false
  showInReports: false
  azRules:
  - scope: filter
    constraint: (memberOf=CN=k8s-test-devs,OU=Groups,DC=example,DC=com)
  - scope: filter
    constraint: (memberOf=CN=k8s-test-admins,OU=Groups,DC=example,DC=com)
```

**Comment by vbottu** [comment]
Hi Marc,
I just tried it ,did not work.  the user is member of both the groups.

**Comment by mlbiam** [comment]
Sorry,  hopefully third time's a charm:

```
apiVersion: openunison.tremolo.io/v1
kind: Org
metadata:
  name: test-cluster
  namespace: openunison
spec:
  description: "TEST K8S CLUSTER"
  uuid: *************************************
  parent: ******************************
  showInPortal: true
  showInRequestAccess: false
  showInReports: false
  azRules:
  - scope: filter
    constraint: (groups=CN=k8s-test-devs,OU=Groups,DC=example,DC=com)
  - scope: filter
    constraint: (groups=CN=k8s-test-admins,OU=Groups,DC=example,DC=com)
```
